### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by anitsh** [open-data/ckanext-canada#1066]
Found a broken link at CKAN at line "Use open-data fork of , branch canada-v2.6"

**Comment by codeanit** [comment]
Looks like there are other broken links as well.

**Comment by JVickery-TBS** [comment]
https://github.com/open-data/ckanext-canada/pull/1344

https://github.com/open-data/ckanext-canada/commit/0be3e2b3bc1d172c71f67a2679a937f8b9613fef
