### ISSUE TITLE
2.8 testing, round 1

### ISSUE THREAD

**Issue by wardi** [open-data/ckanext-canada#1184]
# Test Plan

## 0. Writing awesome bug reports

- include screenshot(s) before bug occurs with URL and login name visible
- include screenshot after bug occurs with URL visible, add arrow(s) to screenshot if necessary
- description of bug can be brief if problem is clear in screenshot(s) 

## 1. Registry

|icon | interaction method |
| --- | --- |
| ⚫ | console server access |
| 🔴 | sysadmin user web |
| 🔵 | admin user web |
| 🔘 | editor user web |

### 1.1 Initializing an empty db (not required for existing sites)

- [ ] ⚫ create/update organizations with `ckanapi load organizations -I transitional_orgs.jsonl`
- [ ] ⚫ create/set 🔴 sysadmin user with `ckan --plugin=ckan sysadmin add <user>`
- [ ] ⚫ export organizations with `ckanapi dump organizations | bin/transitional_org_filter.py > exported_orgs.jsonl`
  - [ ] ⚫ verify no differences with imported `transitional_orgs.jsonl` file
- [ ] ⚫ load datasets with `ckanapi load datasets -zI od-do-canada.jsonl.gz`

### 1.2 Account sign-up and approval

- [x] 🔵 new admin visit front page then fills request account form
  - [x] 🔵 retrieves confirmation email
  - [x] 🔵 log in and see limited home page with no access to records (yet)
- [ ] 🔴 sysadmin received an email notification of the new account request
- [x] 🔴 sysadmin user assigns 🔵 admin user to an existing organization as an Admin
- [x] 🔘 editor user signs up as above
- [x] 🔵 admin user assigns 🔘 editor user to an organization as an Editor
- [x] 🔘 editor user resets password with password reset form
  - [ ] 🔘 retrieve reset email and follow link
  - [ ] 🔘 log in with new password

### 1.3 Asset creation, editing and publishing

- [x] 🔘 editor user creates new dataset
  - [x] 🔘 submit dataset form with missing values, verify all required fields marked as errors
  - [x] 🔘 fill and submit complete dataset marked ready to publish, proceed to add a resource
  - [x] 🔘 submit resource form with missing values, verify all required fields marked as errors
  - [x] 🔘 fill and submit complete resource with uploaded file, proceed to add another resource
  - [x] 🔘 fill and submit complete related item, save dataset
  - [x] 🔘 verify dataset, resource and related items display as expected
- [x] 🔘 editor user creates new information asset
  - [x] 🔘 submit asset form with missing values, verify all required fields marked as errors
  - [x] 🔘 fill and submit complete asset marked ready to publish, proceed to add a resource
  - [x] 🔘 submit resource form with missing values, verify all required fields marked as errors
  - [x] 🔘 fill and submit complete resource with uploaded file, proceed to add another resource
  - [x] 🔘 fill and submit complete related item, save asset
  - [x] 🔘 verify asset, resource and related items display as expected
- [x] 🔴 sysadmin views publish datasets page and sees one dataset and one information asset
  - [x] 🔴 publish both and see no more datasets to publish
  - [x] PORTAL: wait for publishing job and verify published dataset and information asset are now on the portal
  - [x] 🔴 edit the dataset just published and remove the "portal release date" value
  - [x] 🔴 visit the dataset publishing page to confirm that the dataset reappears
  - [x] PORTAL: wait for publishing job and verify that dataset was removed from the portal

### 1.4 Suggested dataset updates

- [x] 🔘 editor user add multiple status updates to a suggestion
  - [x] 🔘 verify that updates are re-sorted into correct date order on save
  - [x] 🔘 verify that required fields are enforced by the form
  - [x] 🔘 remove some updates and check that they are properly removed
  - [x] PORTAL: wait for publishing job and verify that status updates are displayed

### 1.5 Organization changes

- [x] 🔴 sysadmin create a new organization, verify that it appears in org list
- [x] 🔵 admin user edit details of their organization
  - [x] 🔵 verify that title change appears in org list
  - [ ] 🔵 create a new proactive disclosure record with the new organization
  - [x] 🔵 create a new dataset with the new organization
  - [x] ⚫ reindex datasets for this organization with `paster --plugin=ckan search-index rebuild -r -e`
  - [x] 🔵 verify that org title change has been applied to datasets

### 1.6 Proactive disclosure

- [x] 🔘 editor user visit one of the PD types with enforced validation (e.g. consultations or contracts)
  - [x] 🔘 download excel template and fill see that errors and missing fields are hilighted as text is entered
  - [x] 🔘 upload excel template with two new records
  - [x] 🔘 verify new records are displayed in the preview table
  - [x] 🔘 select records in preview and click edit in excel to download pre-populated template
  - [ ] 🔘 verify that records appear in downloaded template and can be re-uploaded with changes
  - [x] 🔘 select and delete records from the preview table
  - [x] ⚫ publish changes to search and exported csv file with e.g. `make -f bin/pd/Makefile consultations`
  - [ ] PORTAL: verify updated records visible on search and exported csv

### 1.7 User management
 - [ ] 🔘 editor user click the View Members of your Organization link, see list of users but unable to make changes
 - [ ] 🔵 admin user click the View Members of your Organization link, see list of users with option to make changes

## 2. Portal

- [x] view dataset and resource pages
  - [x] verify formatting and display of all fields
  - [x] verify display of map (e.g. for the [open data portal catalogue](https://open.canada.ca/data/en/dataset/c4c5c7f1-bfa6-4ff6-b4a0-c164cb2060f7))
  - [ ] verify similar records are shown and appropriate
  - [x] verify rate this dataset links to Drupal rating page and shows ratings
  - [ ] verify the comments feature works and links to Drupal
- [ ] download an uploaded resource from a dataset page
- [x] follow link to an external resource from a dataset page

**Comment by wardi** [comment]
@HoussamBedja @RabiaSajjad @thriuin @PatLittle I'm maintaining an evolving copy of this test plan at https://github.com/open-data/ckanext-canada/blob/master/docs/test-plan.md so if you want to add/update any items for the next round of testing please make changes to that file. For the next round of testing copy the [content](https://raw.githubusercontent.com/open-data/ckanext-canada/master/docs/test-plan.md) into a new ticket like this one.

**Comment by paulnoble02** [comment]
@wardi I am unable to select the checkbox beside each test, guessing I am missing a permission or I am not assigned to this project?
