### ISSUE TITLE
Question: language-specific URLs

### ISSUE THREAD

**Issue by nfee006** [open-data/ckanext-canada#1185]
Hi - not an issue, just a question.

My group at CSA has used ckanext-canada to develop our own data portal  (https://github.com/asc-csa/ckanext-asc-csa). I was wondering how your group went about implementing language-specific urls (open.canada.ca and ouvert.canada.ca) - assuming that you're involved with the implementation of that site. Was this done within CKAN or just server-side? 

Thanks,
Natasha

**Comment by wardi** [comment]
Hi Natasha,

We use nginx to serve the same site from different domain names and redirect when a user switches languages. It's not a perfect solution because the site url specified in the ini file only points to one domain, but that only comes up when generating absolute paths.

**Comment by nfee006** [comment]
Thank you!
