### ISSUE TITLE
Move mandatory config into IConfigurer plugin(s)

### ISSUE THREAD

**Issue by ThrawnCA** [open-data/ckanext-canada#1434]
Required configuration entries could be applied automatically by the plugins.

For example, `CanadaSecurityPlugin` could be made to automatically set `ckan.auth.create_dataset_if_not_in_organization = False`, by implementing `IConfigurer`.

**Comment by JVickery-TBS** [comment]
`ckan.auth` settings set specifically in `CanadaSecurityPlugin` class: https://github.com/open-data/ckanext-canada/commit/e45e5797f3cc261fab9f84684e749af19c5fec76

Allowed `ckan.auth.create_user_via_api` to be set in INI files still just for development servers / local development automation.

**Comment by ThrawnCA** [comment]
README should be updated to reflect the automatic config.
