### ISSUE TITLE
Publisher list is empty in create dataset

### ISSUE THREAD

**Issue by josegar74** [open-data/ckanext-canada#747]
I have setup ckanext-canada (using the branch canada-v2.1 as described in https://github.com/open-data/ckanext-canada#ckanext-canada), but I have a issue when trying to create a dataset. 

As you can see in the following screenshot the Publisher selection is empty:

![add-dataset](https://cloud.githubusercontent.com/assets/1695003/19625936/8dd005c2-9926-11e6-91da-f1f378ad986b.png)

In the **Organizations** option, the organisations are listed properly and I also used one of the organization names for the user registration.

![organizations](https://cloud.githubusercontent.com/assets/1695003/19625958/1234684e-9927-11e6-83cb-5455e6dc277b.png)

If anybody can point me to the fix for this would be really appreciated. Apologies as I'm a newbie to ckan, so maybe I'm doing something wrong or I've missed some step in the setup.

**Comment by wardi** [comment]
Thank you for your interest in our extension! All the latest development is on the canada-v2.5 branch. We're going to be merging that to master now that we've deployed to our production sites. Try following the README on that branch.

**Comment by josegar74** [comment]
I've installed canada-v2.5 branch and got it working, but with the new version I don't see any option to create datasets as in the previous version:

![v2 5](https://cloud.githubusercontent.com/assets/1695003/19681134/94b2ec8c-9aa8-11e6-99a2-f2b867f6f76f.png)

In the developer tools of Chrome I see some 404 for these files, not sure if that can be related:

http://127.0.0.1:5000/wet_no_menu_loader
http://127.0.0.1:5000/canada.css
http://127.0.0.1:5000/theme-wet-boew/js/theme.min.js

For the last one, I downloaded the package as described in https://github.com/open-data/ckanext-wet-boew/tree/wet4-scheming, but this download doesn't contain any js folder:

```
mkdir theme-wet-boew && curl -L https://github.com/wet-boew/themes-cdn/archive/$WET_VERSION-theme-wet-boew.tar.gz | tar -zx --strip-components 1 --directory=theme-wet-boew
```

```
$ ls theme-wet-boew/
assets  css  Licence-fr.txt  License-en.txt
```

Can you confirm how to create new datasets from the UI?

I have a project, where I have to push geospatial datasets to CKAN Canada version using the CKAN API and would like to check if you have any Docker image published with the application already setup, that would be really useful.

**Comment by josegar74** [comment]
I could manage to create an admin user, using `paster` and with that user can use the CKAN API and access to create new datasets. I was expecting that could be managed in the UI, but thats ok also.

I have an additional question:

- When adding a new dataset the Collection Type field is fixed to non-spatial. Is not possible to create geo-spatial datasets? I think in the version 2.1 there're some geo-spatial fields.

**Comment by wardi** [comment]
The form is only set up for the datasets that are registered manually, which for now are the non-spatial ones, because that's all that was required. There are a number of geo fields that are part of the schema but can only be set from the API right now, because we only harvest them from other systems.

**Comment by josegar74** [comment]
Thanks for the clarification. The system I'm working on uses the API, will use the geo-spatial fields.

**Comment by josegar74** [comment]
I have some additional question, about the CKAN schema (I'm using this one: https://github.com/open-data/ckanext-canada/blob/canada-v2.5/ckanext/canada/metadata_schema/schema.json): 

* Some fields like `hierarchy_level` seem not described in that file and can be used in the API (An example document with that field: http://open.canada.ca/data/api/action/package_show?id=2e6f97df-eeae-462b-902d-4453a1c1034b. Is there any other document that I should check instead?

**Comment by wardi** [comment]
Don't look at that schema, that was our 2.1 schema definition that I haven't been able to remove quite yet. Take a look at chanext/canada/schema/dataset.yaml and presets.yaml. Our schema is implemented with the ckanext-scheming and ckanext-fluent extensions now.

**Comment by wardi** [comment]
Sounds like your original issue was resolved, closing.
