### ISSUE TITLE
Cell formatting changes across the consultation registry dataset

### ISSUE THREAD

**Issue by RachelMuston** [open-data/ckanext-canada#902]
We have noticed the following issue...
In our data template, some of our columns are formatted as Text.  However when we download the full dataset, some cells have been changed from 'Text' to 'General' (and those cells are being recognized as a number (instead of the text showing in the 'sample' box, all I see are #######).
Wondering if this is an issue in uploading, or people using different versions of Excel or if this is just a user problem e.g. the user changed the format of the cell directly.
Also wondering, if this is a user problem, if this is something that can be fixed during uploading - e.g. to force all the cells back into the right format.
Thanks! :)

**Comment by wardi** [comment]
Hi @RachelMuston,

How are you downloading the full dataset? We don't currently have an export to Excel option, are you using the CSV files published on the portal?

**Comment by RachelMuston** [comment]
Hi @wardi,
Yep, using the CSV file on the portal.  @marybethbaker and I have been playing with this.  Determined that the issue was due to the importer for Excel - even though items were clearly text (and in"") the importer was changing all the columns to 'General' - which then was recognizing some text cells as numbers.  Thanks for getting back to us so fast! :)

**Comment by wardi** [comment]
@RachelMuston many users copy and "paste as text" the values from the preview table back into their templates to edit them. Re-uploading all records when only changing a few might be slow(though the systems has been able to handle it so far)

An "Export to Excel Template"  button would be a nice feature to add to this screen (for the records displayed). Should be easy to add but it hasn't been requested yet.
