### ISSUE TITLE
crown copyright notice

### ISSUE THREAD

**Issue by royfielding** [open-data/ckanext-canada#940]
IANAL, but according to

https://www.canada.ca/en/canadian-heritage/services/crown-copyright-request.html

the correct notice for a crown copyright is

© Her Majesty the Queen in Right of Canada, as represented by the Minister of (legal departmental name), (year of publication).

Though I personally think that is overkill -- in the US, there is no need to include a copyright notice unless you intend to sue for infringement. However, the current notice is definitely wrong since "Government of Canada" is not allowed to own the copyright and it is actually illegal in most countries to include an invalid notice. Far better to have none at all.

**Comment by wardi** [comment]
@PatLittle Do you have the translation for this?

**Comment by royfielding** [comment]
Obviously, it would be easier to maintain as simply

© The Crown in Right of Canada, (year of publication).

but you might need to get some sort of official approval for that.

BTW, if you have already obtained legal approval for the existing text, please just indicate that and you can close this issue right away. My only concern is that it be an allowed notice. BTW, in the US at least, it is also fine to exclude the legal notice and simply state the license as is, assuming you have no intention of suing for infringement.

YMMV, IANAL, and am not even a Canadian resident. Cheers.

**Comment by PatLittle** [comment]
> @PatLittle Do you have the translation for this?

Here is the official version with translation. 

© Her Majesty the Queen in Right of Canada, represented by the President of the Treasury Board, 2018
© Sa Majesté la Reine du chef du Canada, représentée par le président du Conseil du Trésor, 2018

**Comment by wardi** [comment]
Thanks Pat!  I'll use `2012-2018` in this repo since that's when we started on this one.

I'll make the same change to our other repositories here and in the ckan github org.

**Comment by wardi** [comment]
fixed by https://github.com/open-data/ckanext-canada/commit/2610fd7e8f0d5df44d0b7f596d38e7ef4a95814f

**Comment by wardi** [comment]
d'oh, I've already pushed this change to 7 repositories.

Well, we're using `Copyright` fully spelled out so I can't imagine the `(c)` hurts. I'll replace the `(c)` and remove the range next time. Intent matters a lot more for lawyers than for interpreters and compilers!

Thank you for this @royfielding !

**Comment by royfielding** [comment]
Oh, I need to take some of that back … Canada (unlike the US) does not have a specific legal form of copyright marking, though it is still [recommended to use the same as other countries](http://www.ic.gc.ca/eic/site/cipointernet-internetopic.nsf/eng/h_wr02281.html?Open&wt_src=cipo-cpyrght-main&wt_cxt=learn#indicatingCopyright).  Anyway, the change you committed is good.
